server:
  port: 7000

spring:
  application:
    name: auth-redis
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      loadbalancer:
        mode: service
      discovery:
        enabled: true
#      client:
#        namespace: hup-ns