# 后端服务url前缀
backend-service-alias: "/cloud-service"
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'${backend-service-alias}/'+serviceId+'/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'${backend-service-alias}/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
      loadbalancer:
        use404: true
